name: "Upload to caches"
on:
  pull_request:
  push:
jobs:
  cachix-build:
    strategy:
      matrix:
        system:
          - ubuntu-latest
          - macos-latest
        isMain:
          - ${{ contains(github.ref, 'main') }}
        # Excluded emulated builds on PRs
        exclude:
          - system: aarch64-linux
            isMain: false
          - system: x86_64-darwin
            isMain: false
      fail-fast: false
    runs-on: ${{ matrix.system }}
    env:
      EXTRA_NIX_CONFIG: |
        extra-trusted-public-keys = public:AdkE6qSLmWKFX4AptLFl+n+RTPIo1lrBhT2sPgfg5s4=
          extra-substituters = https://cache.jzbor.de/public
    steps:
      - uses: actions/checkout@v4

      - name: "Install Nix"
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            ${{ env.EXTRA_NIX_CONFIG }}

      - name: "Setup Attic cache"
        uses: ryanccn/attic-action@v0
        with:
          endpoint: ${{ vars.ATTIC_ENDPOINT }}
          cache: ${{ vars.ATTIC_CACHE }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - uses: cachix/cachix-action@v14
        with:
          name: dojo-nix
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          skipPush: true

      - name: "Determine package architecture"
        id: determine-architecture
        run: |
          printf 'arch=%s\n' "$(echo '${{ matrix.package }}' | cut -d. -f1)" | tee -a $GITHUB_OUTPUT

      - name: Omnix CI
        run: |
          nix run github:juspay/omnix -- ci \
            --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} \
            run \
              --systems "${{ steps.determine-architecture.outputs.arch }}" \
              --results=$HOME/omci.json
      # Push the Nix cache
      - name: Push to cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        if: env.BRANCH_NAME == 'main'
        run: |
          nix run github:juspay/cachix-push -- \
            --cache dojo-nix \
            < $HOME/omci.json
      - name: Push to attic
        if: env.BRANCH_NAME == 'main'
        run: |
          cat $HOME/results.json \
           | nix run nixpkgs#jq -- '.result.ROOT.build.outPaths.[]' -r \
           | nix run github:zhaofengli/attic -- push cairo-nix --stdin
